import { TanstackProvider } from "@/providers/TanstackProvider";
import theme from "@/theme";
import { ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../style/GlobalStyle.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Rate Calendar App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body style={{ margin: 0 }}>
				<AppRouterCacheProvider>
					<ThemeProvider theme={theme}>
						<TanstackProvider>
							<main>{children}</main>
						</TanstackProvider>
					</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}

